#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-swap
# REQUIRE: zfs
# BEFORE: savecore

. /etc/rc.subr

generate_fstab_swap()
{
	ls -1 /dev/mirror 2>/dev/null | awk '/^swap[0-9]+$/ {print "/dev/mirror/" $1 ".eli", "none", "swap", "sw", 0, 0}'
}

generate_fstab()
{
    generate_fstab_swap >> /etc/fstab
    service swap start
}

name="ix-swap"
start_cmd='generate_fstab'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
